images/singleuser-sample/Dockerfile
Reverts jupyterhub/helm-chart#15
From https://github.com/jupyterhub/helm-chart/pull/15#issuecomment-300548967:
> 1. This makes the image being built non-deterministic. It'll get a different version of pip each time we build it.
> 2. It adds another axes to the package management set of axes (ubuntu version, python version, pip version). Ideally I want ubuntu version to imply both python and pip version, so we can just say 'ubuntu 17.04' rather than 'ubuntu 17.04 and pip 9.0.1', since the latter implies variants we might have to also support ('ubuntu 17.04 and pip 8.x', 'ubuntu 17.04 and pip 10')
> 3. Ubuntu 17.04 actually has pip 9.0, so should solve our problems. Upgrading the FROM to 17.04 is welcome, and I might do that soon myself :)
I'm a fan of using pip to upgrade itself when we're …
=> Revert "Upgrade pip because upgrade pip."

README.md
Noticed this wasn't linking to the right spot.
=> fixing link to zero-to-jupyterhub readthedocs

images/hub/jupyterhub_config.py, jupyterhub/templates/hub.yaml
This updates the Jupyterhub image in order to enable GitHub authorization.
Should close https://github.com/jupyterhub/helm-chart/issues/30 once the standard images are rebuilt.
=> Githubauth

Makefile, images/proxy/Dockerfile, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
simplifies proxy image, makes behavior more consistent with defaults
With JupyterHub 0.8, we can hopefully switch to kubernetes ingress
@yuvipanda does switching the default to CHP here make it difficult for you to use nginx-chp in your deployments as needed? Do we need to solve #1 for that?
=> use configurable-http-proxy by default

images/hub/jupyterhub_config.py
This is a Berkeley-specific remnant for git config, which should eventually be moved to Berkeley stuff.
This patch is needed for GitHub OAuth to work.
=> temp fix: set default email_domain to 'local'

jupyterhub/templates/hub/configmap.yaml
Here's what I have in my config.yaml:
```
hub:
...
extraConfigVars:
secret_key: "hello_world"
timeout_value: 240
```
And in the pod:
```bash
$ kubectl exec hub-deployment-2390299585-wgz9k -- cat /etc/jupyterhub/config/hub.extra-vars
{"secret_key":"hello_world","timeout_value":240}
```
=> Allow setting hub related variables in config map.

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/proxy/deployment.yaml, jupyterhub/values.yaml
This makes it easier to iterate on a debug image which has the same tag.
When debugging, in config.yaml, set:
```bash
hub:
imagePullPolicy: Always
```
After that, change image code and re-upload Docker image. There's no need
to edit config.yaml after each reupload.
When not debugging, we default to ifNotPresent.
Here's [another explanation](https://kukulinski.com/10-most-common-reasons-kubernetes-deployments-fail-part-2/#10containerimagenotupdating).
How did I test this?
* Step 1: I've set imagePullPolicy to "Always" in config.yaml.
* Step 2: Upload initial image, it adds a line to `jupyterhub_config.py`.
```bash
$ kubectl exec hub-deployment-2875592925-659z1  -- cat /srv/jupyterhub_config.py | grep "hi there"
```
* Step 3: Update this line to say "hi there 2", rebuild image, upgrade. …
=> Allow for custom imagePullPolicy for hub.

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
Without modifying jupyterhub_config.py
Example: in config.yaml, add this:
```bash
auth:
type: "custom"
custom:
className: "hashauthenticator.HashAuthenticator"
params:
secret_key: "834e6cace4747e966c002737191619f583be814557d3f11e358232a9a28dfa7d"
```
I have verified that this works by doing the following:
* Step 1: I copied the hub image and built my own version, using the code from this branch.
* Step 2: I made a new image derived from the one built in step 1. Looks like this:
```bash
$ cat ./docker-images/helm-hub-derived/Dockerfile 
FROM gcr.io/mooc-hub/helm-hub:43e48f9-debug
RUN pip3 install --no-cache-dir jupyterhub-hashauthenticator
```
* Step 3: I redeployed and confirmed that I use the specified authenticator.
```bash
$ ./hub-api.sh GET info
{
"spawner": {
"version": "unknown", …
```
=> Custom authenticator support

jupyterhub/templates/hub/deployment.yaml, jupyterhub/templates/hub/secret.yaml
default behavior when cookie secret is null is already fine because it will create jupyterhub_cookie_secret file in the db volume directory
cookieSecret is only necessary if there isn’t a volume mounted for the hub (i.e. sqlite db)
Even if not set, the only consequence is that rebooting the hub logs out users.
The non-sqlite case is not validated, however. It would probably be nice to fail with an informative error if the db is external and cookieSecret is not set, but I don't know how to do that.
=> only set cookie secret env if specified

images/hub/Dockerfile
=> remove deprecated --no-ssl arg from hub image

jupyterhub/templates/ingress.yaml
We don't want to keep TLS keys in config.yaml - so user will
have to manually create & rotate TLS secrets.
=> Allow setting up TLS manually

jupyterhub/templates/ingress.yaml
Reverts jupyterhub/helm-chart#54 
Sorry, this doesn't actually work yet.
=> Revert "Allow setting up TLS manually"

images/hub/jupyterhub_config.py, jupyterhub/templates/hub/configmap.yaml
@yuvipanda ... added in those items to handle authentication with gitlab in the helm-chart.
=> enable jupyterhub_config.py and configmap.yaml for handling gitlab auth

images/hub/Dockerfile
I'm working on binderhub creating things via the API, eliminating use of tmpauthenticator.
Initially, I thought this needed jupyterhub 0.8, but now I believe we can do all of this in Binder with 0.7 by launching jupyter-notebook instead of jupyterhub-singleuser.
=> add nullauthenticator

index.yaml
0.3-0.4 release dates from git were inaccurate due to a migration in August.
Looked up the dates of the zero-to-jupyterhub tags and entered them manually here.
Dates for all releases will no longer be recomputed, so this should stick.
=> manually fix release dates on old jupyterhub releases

index.md
This makes it clearer which chart was published when,
since we often have multiple publications per day
=> Put time in helm chart publication dates too

index.md, index.yaml
so that `--version=0.6` works, which may be less surprising as the docs are update for 0.7 which fixes the spurious "v" prefix. Only index entries are added, they point to the exact same chart.
=> add v-less aliases for previous hub releases

README.md
This adds a table to the readme that we can use to list important version numbers of various software in the helm chart. AFAIK, the most important thing is JupyterHub, so right now that's the only thing in there.
I'm actually not sure which versions of JupyterHub are in each helm chart so I've put XXX as a placeholder. Can somebody point me to a place where this information exists? Alternatively feel free to suggest changes to the PR to update the values! (maybe @consideRatio or @yuvipanda knows?)
=> jupyterhub versions in readme

README.md
To address https://blog.jupyter.org/open-redirect-vulnerability-in-jupyter-jupyterhub-adf43583f1e4.
=> Update 0.8 to 0.8.1.

_config.yml, index.md
- Remove invalid mix of HTML and markdown (View source on https://jupyterhub.github.io/helm-chart/ and you'll see), replaced with Jekyll templated markdown only
- Include appVersion in table (Closes https://github.com/jupyterhub/helm-chart/issues/106)
- Add a GH pages theme instead of the default one which is a bit sparse- though I'm happy to revert this change.
Preview available at https://www.manicstreetpreacher.co.uk/helm-chart/
In addition we've considered using this repo for other Helm charts (can't remember which repo/issue this came up on). With this change all charts should automatically appear under development without changes to this template. To add a new chart as stable just requires adding it to the list in `_config.yml`
=> Rewrite index.md

artifacthub-repo.yml
In https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1820 I tried adding this file to z2jh repo before but what matters is the actual content served by the helm chart repo webserver: gh-pages content of this repo.
Outcomes:
- The JupyterHub org on artifactshub.io becomes the verified publisher of the jupyterhub helm chart repo on artifactshub.io
- The published versions become restricted to tagged releases like 1.2.3 and 1.2.3-alpha.x and 1.2.3-beta.x but excludes all other versions.
Future:
- More members of the jupyterhub team create accounts on https://artifacthub.io/ so I can invite them as members of the JupyterHub org I've created there.
=> artifacts hub: verify ownership / don't list dev versions

artifacthub-repo.yml
https://github.com/jupyterhub/helm-chart/pull/114 didn't seem to have any effect, so I guess it could be the fact that I used YAML anchors. So, in this PR I remove them.
I also tweak the ignore pattern, and stop ignoring binderhub dev versions as its all thats relevant for binderhub atm.
=> artifacts hub: second attempt

artifacthub-repo.yml
I depublish the pebble helm chart from artifacthub.io so we can acquire official status for the other helm charts in the repo.
This is needed because https://github.com/artifacthub/hub/issues/972, but may not be needed in the future.
=> Let pebble be ignored by artifacthub.io for official status

README.md
Mostly `jupyterhub.github.io` ➡️ `hub.jupyter.org`
=> Update README.md github links
